#!/bin/bash

BSPWMRC=~/.config/bspwm/bspwmrc

focused_color=$(( $2 + 3 ))
normal_color=$(( $3 + 3 ))

focused=$(cat $1 | head -n $focused_color | tail -n 1 | awk '{print $2}')
normal=$(cat $1 | head -n $normal_color | tail -n 1 | awk '{print $2}')

sed -i "s/^BSPWM_NORMAL_BORDER.*$/BSPWM_NORMAL_BORDER_COLOR=$normal/g" \
    "$BSPWMRC"
sed -i "s/^BSPWM_FOCUSED_BORDER.*$/BSPWM_FOCUSED_BORDER_COLOR=$focused/g" \
    "$BSPWMRC"

focused="${focused%\"}"
focused="${focused#\"}"
normal="${normal%\"}"
normal="${normal#\"}"

bspc config normal_border_color  $normal
bspc config focused_border_color $focused
