#!/bin/sh

BSPWM_NORMAL_BORDER_COLOR="#456472"
BSPWM_FOCUSED_BORDER_COLOR="#63a690"

bspc config border_width         3
bspc config window_gap           8
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config normal_border_color  $BSPWM_NORMAL_BORDER_COLOR
bspc config focused_border_color $BSPWM_FOCUSED_BORDER_COLOR

bspc monitor -d 1 2 3 4 5

bspc rule -a mpv state=floating
bspc rule -a feh state=floating
bspc rule -a Transmission-gtk state=floating
bspc rule -a Wine state=floating

~/.bar/bar&
