#!/bin/bash

BAR_FIFO=/tmp/bar-fifo
BAR_HEIGHT=28
BAR_FONT="Roboto-12"
BAR_FONT_OFFSET=0
#BAR_FONT='-*-gohufont-medium-*-*-*-11-*-*-*-*-*-*-*'
BAR_WM_NAME=bspwm_bar
#FORECAST_KEY="7d8456c48be3939924604e9a43ea5b57"

export BAR_FIFO BAR_HEIGHT BAR_FONT BAR_WM_NAME BAR_FONT_OFFSET
