#!/bin/bash

. bar_colors

window_gap=$(bspc config window_gap)
screen_width=1920
width=$((screen_width - 2 * window_gap))
geometry="${screen_width}x$BAR_HEIGHT+0+0"
#geometry="${width}x$BAR_HEIGHT+$window_gap+$window_gap"
offset=$BAR_HEIGHT
#offset=$((BAR_HEIGHT + window_gap))

bspc config top_padding $offset

while read line
do
    if (( RANDOM % 2 )); then
        geometry="${screen_width}x$BAR_HEIGHT+0+0"
    fi
    echo $line
done | lemonbar \
    -n "$BAR_WM_NAME" \
    -g "$geometry" \
    -f "$BAR_FONT" \
    -f "-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1" \
    -B "$DEFAULT_BACKGROUND" \
    -F "$DEFAULT_FOREGROUND" | sh
