call plug#begin('~/.vim/plugged')

Plug 'romainl/vim-cool'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'hynek/vim-python-pep8-indent'
Plug 'guns/vim-sexp'
Plug 'tpope/vim-sexp-mappings-for-regular-people'
Plug 'tpope/vim-dispatch'
Plug 'clojure-vim/vim-jack-in'
Plug 'tpope/vim-fireplace'

call plug#end()

syntax on
filetype plugin indent on

set backspace=indent,eol,start
set nocompatible
set history=200
set showcmd
set ruler
set wildmenu
set hidden
set display=truncate
set hlsearch
set scrolloff=5
set laststatus=2

set expandtab
set tabstop=4
set shiftwidth=4

let mapleader = "\<Space>"
let maplocalleader = ","

nnoremap <Leader>fr :browse oldfiles<CR>

" Do incremental searching when it's possible to timeout.
if has('reltime')
  set incsearch
endif

set ttimeout
set ttimeoutlen=100

command! DeleteTrailingWhitespace %s/ \+$//
