call plug#begin('~/.vim/plugged')

Plug 'romainl/vim-cool'
Plug 'hynek/vim-python-pep8-indent'
Plug 'guns/vim-sexp'
Plug 'tpope/vim-sexp-mappings-for-regular-people'
Plug 'tpope/vim-dispatch'
Plug 'clojure-vim/vim-jack-in'
Plug 'tpope/vim-fireplace'
Plug 'tpope/vim-fugitive'
Plug 'simnalamburt/vim-mundo'

" Don't let fzf offer to install the binary
if executable('fzf')
  Plug 'junegunn/fzf'
  Plug 'junegunn/fzf.vim'
endif

call plug#end()

syntax on
filetype plugin indent on

packadd! matchit
runtime ftplugin/man.vim

set backspace=indent,eol,start
set nocompatible
set history=200
set showcmd
set ruler
set wildmenu
set hidden
set display=truncate
set hlsearch
set laststatus=2

set expandtab
set tabstop=4
set shiftwidth=4

let mapleader = "\<Space>"
let maplocalleader = ","

nnoremap <Leader>ff :e %:h/<C-D>

" Do incremental searching when it's possible to timeout.
if has('reltime')
  set incsearch
endif

set ttimeout
set ttimeoutlen=100

command! DeleteTrailingWhitespace %s/ \+$//

nnoremap - :e %:h<CR>

nnoremap ]q :cn<CR>
nnoremap [q :cp<CR>

if executable('fzf')
  nnoremap <Leader>pf :Files<CR>
  nnoremap <Leader>fr :History<CR>
else
  nnoremap <Leader>fr :browse oldfiles<CR>
endif

let g:netrw_banner = 0
let g:netrw_list_hide = '\./,\.\./'
